# Generated by Django 2.2 on 2020-09-03 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0006_auto_20200902_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('unit', models.CharField(choices=[(None, 'Select'), ('INCHES', 'inches'), ('CM', 'cm'), ('MM', 'mm')], max_length=45)),
                ('quantity', models.IntegerField()),
                ('printing', models.CharField(choices=[(None, 'Select'), ('YES', 'Yes'), ('NO', 'No')], max_length=45)),
                ('stock', models.CharField(blank=True, choices=[(None, 'Select'), ('12PT', '12pt'), ('14PT', '14pt'), ('16PT', '16pt'), ('18PT', '18pt'), ('20PT', '20pt'), ('22PT', '22pt'), ('CARD STOCK', 'card stock'), ('KRAFT STOCK', 'Kraft Stock'), ('CORRUGATED STOCK', 'Corrugated Stock'), ('RIGID STOCK', 'Rigid Stock'), ('OTHER', 'Other')], max_length=45, null=True)),
                ('art_work', models.FileField(blank=True, null=True, upload_to='art_work/')),
                ('full_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('notes', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='catalogue.Product')),
            ],
        ),
    ]
