# Generated by Django 2.2 on 2020-07-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
