# Generated by Django 2.2 on 2020-09-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20200902_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(max_length=225),
        ),
    ]
